[package]
authors = ["HansiHE <hansihe@hansihe.com>"]
name = "pattern-compiler"
version = "0.1.0"

[dependencies]
either = "1.1.0"
petgraph = "0.4.5"
prettytable-rs = "0.6.7"
derivative = "1.0.0"

util = { path = "../util" }
