[workspace]

members = [
    "hir",
    "diagnostics",
    "frontend",
    "pattern-compiler",
    "util",
    "tools",
    "gen_nif",
    "cps_transform",
    "eir",
    "eir_passes",
    "core_parser",
]
