[package]
name = "libeir_util_number"
version = "0.1.0"
authors = ["Hans Elias B. Josephsen <me@hansihe.com>"]
edition = "2018"

[dependencies]
num-traits = "0.2.8"
num-bigint = { git = "https://github.com/hansihe/num-bigint.git" }