[package]
name = "gen_nif"
version = "0.1.0"
authors = ["Hans Elias B. Josephsen <me@hansihe.com>"]
edition = "2018"

[dependencies]
llvm-sys = "70"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "llvm7-0" }