[package]
name = "eir_passes"
version = "0.1.0"
authors = ["Hans Elias B. Josephsen <me@hansihe.com>"]
edition = "2018"

[dependencies]
eir = { path = "../eir" }
pattern-compiler = { path = "../pattern-compiler" }
matches = "0.1.8"
