[package]
name = "core_erlang_interpreter"
version = "0.1.0"
authors = ["hansihe"]

[dependencies]
num = "0.2"
num-traits = "0.2"
num-bigint = "0.2"
tempdir = "0.3"

core_erlang_compiler = { path = "../compiler" }

