jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    strategy:
      matrix:
        Linux:
          vmImage: ubuntu-16.04

        ${{ if parameters.cross }}:
          MacOs:
            vmImage: macOS-10.13
          Windows:
            vmImage: vs2017-win2016
    pool:
      vmImage: ubuntu-16.04

    steps:
      - template: azure-install-rust.yml
        parameters:
          rust_version: ${{ parameters.rust }}

      - template: azure-clone-patch-otp.yml

      - ${{ each crate in parameters.crates }}:
          - script: cargo test
            env:
              CI: 'True'
            displayName: ${{ crate.key }} - cargo test
            workingDirectory: $(Build.SourcesDirectory)/${{ crate.key }}
