[package]
name = "tools"
version = "0.1.0"
authors = ["Hans Elias B. Josephsen <me@hansihe.com>"]
edition = "2018"

[[bin]]
name = "eir_compile"
path = "src/compile.rs"

[dependencies]
core_erlang_compiler = { path = "../compiler" }
cps_transform = { path = "../cps_transform" }
eir = { path = "../eir" }
#core_erlang_interpreter = { path = "../interpreter" }

clap = "2.33.0"
