[package]
name = "tools"
version = "0.1.0"
authors = ["Hans Elias B. Josephsen <me@hansihe.com>"]

[[bin]]
name = "run_fun"
path = "src/run_fun.rs"

[[bin]]
name = "gen_cfg"
path = "src/gen_cfg.rs"

[[bin]]
name = "gen_eir"
path = "src/gen_eir.rs"

[dependencies]
core_erlang_compiler = { path = "../compiler" }
eir = { path = "../eir" }
#core_erlang_interpreter = { path = "../interpreter" }
