[package]
name = "libeir_passes"
version = "0.1.0"
authors = ["Hans Elias B. Josephsen <me@hansihe.com>"]
edition = "2018"

[dependencies]
libeir_ir = { path = "../libeir_ir" }
libeir_intern = { path = "../libeir_intern" }

pattern-compiler = { path = "../pattern-compiler", features = ["debug_table_print"] }
matches = "0.1.8"

cranelift-entity = "0.30.0"