[package]
name = "cps_transform"
version = "0.1.0"
authors = ["Hans Elias B. Josephsen <me@hansihe.com>"]
edition = "2018"

[dependencies]
#eir = { path = "../eir" }
libeir_util = { path = "../libeir_util" }

petgraph = "0.4.13"
cranelift-entity = "0.30.0"

matches = "0.1.8"
